/**
 * Every absence assertion the guard cannot prove had a population behind it,
 * by `file › test title as written` (or function name), with how many such
 * assertions that scope holds (#609). Generated from the scan in
 * `tests/unit/absence-liveness.test.ts` when the self-contained shape stopped
 * being out of scope, and pasted: never typed.
 *
 * It may only shrink. A converted site (routed through `searched` with a
 * floor, #610-#617) makes its count too high and the guard is red until the
 * count is lowered or the entry removed; a new unjudged absence is red
 * because it is not listed. There is no label, reason or shape that exempts
 * a site: this list is debt, not an allowance.
 */
export const ABSENCE_BURN_DOWN: Readonly<Record<string, number>> = {
  'tests/device/ios/journeys.journey.ts › Journey 5 -- 0 students: the real localised error, no groups': 1,
  'tests/device/ios/journeys.journey.ts › Journey 6 -- more groups than students: the real localised message, no groups rendered': 1,
  'tests/device/ios/journeys.journey.ts › Journey 8b -- MAX_STUDENTS + 1 refused: the real localised message': 1,
  'tests/unit/evidence-page.test.ts › carries an empty set through candidates, files and reconciliation': 1,
  'tests/unit/evidence-page.test.ts › does not claim a recording policy it never had a spec file to read': 1,
  'tests/unit/evidence-page.test.ts › gives it a section although no manifest row names it': 1,
  'tests/unit/evidence-page.test.ts › reads a result with no recording as nothing to embed, not as a loss': 1,
  'tests/unit/feature-terms.test.ts › %j names no feature': 1,
  'tests/unit/feature-terms.test.ts › Chinese and Thai are searched without word breaks: 固定 inside 取消固定 counts': 2,
  "tests/unit/feature-terms.test.ts › any one of a feature's approved words is enough": 1,
  'tests/unit/feature-terms.test.ts › copy carrying an approved word for every feature it names passes': 1,
  'tests/unit/feature-terms.test.ts › copy whose English names no feature is never returned, whatever its rendering': 1,
  'tests/unit/feature-terms.test.ts › neither letter case nor Unicode composition decides it': 2,
  'tests/unit/feature-terms.test.ts › the corrected zh PINNED_MIXED_SEX is not flagged, and says 固定': 1,
  'tests/unit/floorless-searches.test.ts › only shrinks the burn-down list': 1,
  'tests/unit/floorless-searches.test.ts › reads a site in %s as floorless in its test': 1,
  'tests/unit/floorless-searches.test.ts › reads a site in %s by the function name': 1,
  'tests/unit/floors.test.ts › never carries an id no spec spells whole, a prefix of one included': 1,
  'tests/unit/floors.test.ts › never carries an id the unit run asserted': 1,
  'tests/unit/floors.test.ts › says nothing when no figure moved': 1,
  'tests/unit/grouping.test.ts › a lone sex too small for the requested size places with no warning -- there is no other sex to have joined': 1,
  'tests/unit/grouping.test.ts › a roster that is entirely one sex places with no warning': 1,
  "tests/unit/grouping.test.ts › bunches each side's own remainder separately": 1,
  "tests/unit/grouping.test.ts › bunches the boys' own allocated remainder": 1,
  'tests/unit/grouping.test.ts › every current success carries an empty warnings list (sexMode: %s)': 1,
  'tests/unit/grouping.test.ts › finds 3-and-1 when proportional 2-and-2 would refuse a together-unit, instead of refusing (Fix round 1, F-1)': 1,
  'tests/unit/grouping.test.ts › makes single-sex groups when the numbers divide': 1,
  'tests/unit/grouping.test.ts › needs no warning outside separate mode': 1,
  'tests/unit/grouping.test.ts › pins claiming more groups than the teacher requested still succeed, with no warning or error': 1,
  'tests/unit/grouping.test.ts › separate mode places a single-sex pinned group and splits the pool by sex around it': 1,
  'tests/unit/grouping.test.ts › splits 2-and-2 by headcount share, not 3-and-2 by an independently sized per-sex group count': 1,
  'tests/unit/i18n.test.ts › %s has no blank string anywhere': 1,
  'tests/unit/i18n.test.ts › and the list of exceptions has no dead entries': 1,
  'tests/unit/isolated-context-tagging.test.ts › accepts that test once tagged': 1,
  'tests/unit/isolated-context-tagging.test.ts › accepts the identical test once tagged': 1,
  'tests/unit/isolated-context-tagging.test.ts › does not mistake a runtime test.use(...) call for one disabling JavaScript': 1,
  'tests/unit/isolated-context-tagging.test.ts › does not reach into an unrelated sibling describe that happens to share a file': 1,
  'tests/unit/isolated-context-tagging.test.ts › ignores a javaScriptEnabled:false-shaped call when it appears only in a comment': 1,
  'tests/unit/isolated-context-tagging.test.ts › is not confused by a template-literal title containing brace-like interpolation': 1,
  'tests/unit/isolated-context-tagging.test.ts › is not fooled by a declaration spelled inside a string': 1,
  'tests/unit/label-check.test.ts › a capital marks a name: the common words of a label name nothing': 1,
  'tests/unit/layout-widths.test.ts › reads nothing from a condition on anything but the viewport width': 1,
  "tests/unit/literal-floors.test.ts › reads no floor in a callback's own comparison": 1,
  'tests/unit/literal-floors.test.ts › refuses %s by line, never skips it': 1,
  'tests/unit/locale-metadata.test.ts › gives every language a distinct, non-blank native name': 1,
  'tests/unit/nav-timings.test.ts › excuses nothing when the report carries no project config': 1,
  'tests/unit/nav-timings.test.ts › ignores a test.step a human happened to title Navigate': 1,
  'tests/unit/nav-timings.test.ts › ignores the other pw:api steps that surround every navigation': 1,
  'tests/unit/nav-timings.test.ts › survives a run that recorded nothing rather than dividing by zero': 1,
  'tests/unit/one-test-per-case.test.ts › passes a loop that changes no page state': 1,
  'tests/unit/one-test-per-case.test.ts › passes a runtime population that says so in a comment': 1,
  'tests/unit/one-test-per-case.test.ts › passes the same cases generated as one test each': 1,
  'tests/unit/one-test-per-case.test.ts › refuses a loop whose navigation sits in a shared helper (#390 F152)': 1,
  'tests/unit/palette.test.ts › lists all 2^n subsets, each keeping the original order': 1,
  'tests/unit/parked-tests.test.ts › accepts a reference in a comment block above, however many comments it runs to': 1,
  'tests/unit/parked-tests.test.ts › accepts a reference on the wrapped title line': 1,
  'tests/unit/parked-tests.test.ts › accepts a test.fixme whose own title names an issue': 1,
  'tests/unit/parked-tests.test.ts › accepts a test.fixme whose preceding comment names an issue': 1,
  'tests/unit/parked-tests.test.ts › does not treat a test.fixme quoted inside a comment as a declaration': 1,
  'tests/unit/parked-tests.test.ts › is blind to the runtime conditional overload, which needs no issue': 1,
  'tests/unit/parked-tests.test.ts › is not fooled by a parked declaration spelled inside a string': 1,
  'tests/unit/pipeline-wiring.test.ts › does not read the locked copy, or a global install of something else': 1,
  'tests/unit/remote-images.test.ts › finds nothing in a config that authorises no remote image': 1,
  'tests/unit/remote-images.test.ts › is not satisfied, nor refused, by a comment naming a domain': 1,
  'tests/unit/report-review.test.ts › reads an empty table as no reports': 1,
  'tests/unit/report.test.ts › %s: glory-points carries every leaf of site.glory and none of site.home': 1,
  'tests/unit/report.test.ts › a nonsense quote matches nothing on any page in any locale': 1,
  'tests/unit/report.test.ts › matches nothing for text that is not on the page': 2,
  'tests/unit/report.test.ts › no footer page offers the 404 copy': 1,
  'tests/unit/report.test.ts › offers only its own page: a home string is not found on glory-points': 1,
  'tests/unit/report.test.ts › refuses a fragment that spans a slot without being the whole message': 1,
  'tests/unit/report.test.ts › rule 2 counts Thai graphemes, not code points': 1,
  'tests/unit/report.test.ts › rule 2 refuses one character and accepts two': 1,
  'tests/unit/roster.test.ts › an absent student holding one side of a clash does not trigger it': 1,
  'tests/unit/roster.test.ts › an absent student still counts as holding their number, closing the gap': 1,
  'tests/unit/roster.test.ts › does not treat a roster starting above 1 as a gap': 1,
  'tests/unit/roster.test.ts › is quiet on a single-student roster, however it is numbered': 1,
  'tests/unit/roster.test.ts › is quiet on an empty roster': 2,
  'tests/unit/roster.test.ts › is quiet when a duplicate, not a gap, is what is wrong': 1,
  'tests/unit/roster.test.ts › is quiet when the numbers run without gaps': 1,
  'tests/unit/roster.test.ts › is quiet when the same apart letter is on students not kept together': 1,
  'tests/unit/roster.test.ts › returns nothing, promptly, for a range wider than MAX_ROSTER': 1,
  'tests/unit/roster.test.ts › warns up to the limit and stops beyond it': 1,
  'tests/unit/route-coverage.test.ts › does not read a route that only starts with the same letters': 1,
  'tests/unit/scoped-classes.test.ts › checks only what Astro scopes: not is:global, not is:inline, not :global()': 1,
  'tests/unit/scoped-classes.test.ts › recognises a class a script adds to an element the page built: %s': 1,
  'tests/unit/source-files.test.ts › names nothing when the two agree, in any order': 1,
  'tests/unit/source-text.test.ts › finds no CSS in a file with no style': 1,
  'tests/unit/source-text.test.ts › finds no code in a file with no frontmatter and no script': 1,
  'tests/unit/source-text.test.ts › finds none where comment syntax is quoted': 1,
  'tests/unit/translate-messages.test.ts › sends copy as it is, a message as its sentences, and a symbol not at all': 1,
  'tests/unit/upload-assets.test.ts › reads an empty store as empty, because that is what a first run sees': 1,
  'tests/unit/viewport-tagging.test.ts › accepts a page.viewportSize() read in a tagged test that resizes': 1,
  'tests/unit/viewport-tagging.test.ts › accepts the identical test once the tag is added': 1,
  'tests/unit/viewport-tagging.test.ts › attributes test.use({ viewport }) to its enclosing describe, both directions': 1,
  'tests/unit/viewport-tagging.test.ts › does not mistake a runtime test.skip(condition, reason) call for a new declaration': 1,
  'tests/unit/viewport-tagging.test.ts › ignores setViewportSize and a declaration-shaped call when they appear only in a comment': 1,
  'tests/unit/viewport-tagging.test.ts › is not fooled by a declaration spelled inside a string': 1,
  'tests/unit/viewport-tagging.test.ts › tolerates a wrapped title (test( on one line, the quoted title on the next)': 1,
  'tests/unit/workflow-jobs.test.ts › excuses the aggregate from asking for success in its condition': 1,
  'tests/unit/workflow-jobs.test.ts › lists GITHUB_TOKEN like any other secret, and none for a job reading none': 1,
  'tests/unit/workflow-jobs.test.ts › lists no scripts for a job with no steps': 1,
  'tests/unit/workflow-jobs.test.ts › reads a job-level uses: as the workflow the job calls': 1,
};
