/**
 * Every `searched` site whose test checks no floor on the population it
 * searched, by `file › test title as written` (or function name), with how
 * many such sites that scope holds (#515). Measured by `searchSitesIn` when
 * the meta-guard landed (274 sites in 263 scopes) and again when #534 bound
 * each floor to its search's own population: 290 sites in 274 scopes.
 *
 * It may only shrink. A converted site makes its count too high, and
 * `floorless-searches.test.ts` is red until the count is lowered or the
 * entry removed; a new floorless site is red because it is not listed.
 */
export const FLOORLESS: Readonly<Record<string, number>> = {
  'tests/device/ios/journeys.journey.ts › `Journey 14 -- iOS-only, ${shape.what}: ${shape.count} pupils in ${shape.size}s on the projector board, with the fullscreen grant refused by the phone itself`': 1,
  'tests/e2e/baseurl-guard.spec.ts › every baseURL-aware API call on a relative URL is one the device fixtures actually resolve': 1,
  'tests/e2e/chrome.spec.ts › `${locale}: the footer names no company, and still reaches a person`': 1,
  'tests/e2e/classroom-groups-controls.spec.ts › `no horizontal scroll at ${width}px with any single section open — ${path}, every section derived`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › `every row still declares its own absence after ${what}`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding absent pupils removes the Absent column and only that column': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding the letters removes Sex, Together and Apart, and only those': 1,
  'tests/e2e/classroom-groups-print.spec.ts › showing absent pupils prints every column, including Absent': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › `${path}: no control holding typed text is submittable`': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › and nothing about them is written to storage': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › submitting cannot put a class list in the URL': 1,
  'tests/e2e/classroom-groups-projector.spec.ts › expectNothingOutOfReach': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `every roster control meets the 44px touch target with a placeholder showing -- ${path}`': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `no dropdown ever truncates its own column name -- ${path} at ${width}px`': 1,
  'tests/e2e/copy-reaches-a-page.spec.ts › `${locale}: no defined copy renders nowhere`': 3,
  'tests/e2e/copy-reaches-a-page.spec.ts › every page in every locale': 1,
  'tests/e2e/disabled-controls.spec.ts › `${theme}: the disabled placeholder option is excluded deliberately, and it exists`': 1,
  'tests/e2e/disabled-controls.spec.ts › `at 320px every disabled control keeps a 44px target, and the page does not scroll sideways -- ${path}`': 1,
  'tests/e2e/disabled-controls.spec.ts › default state — every disabled control shows the no-entry cursor': 1,
  'tests/e2e/disabled-controls.spec.ts › expectAReasonWithoutHover': 1,
  'tests/e2e/disabled-controls.spec.ts › expectDisabledPaint': 1,
  'tests/e2e/disabled-controls.spec.ts › expectNoEntryCursor': 1,
  'tests/e2e/disabled-controls.spec.ts › only checkbox, radio and file inputs are left to the UA to paint': 1,
  'tests/e2e/disabled-controls.spec.ts › the no-entry cursor marks the disabled controls apart from the enabled ones': 1,
  'tests/e2e/header-room.spec.ts › expectRoom': 2,
  "tests/e2e/locale-beta.spec.ts › `${locale}: the badge's spoken label keeps the page's language, even inside another language's entry`": 1,
  'tests/e2e/not-found-report.spec.ts › `${locale}: every control is at least 44px and every text meets AA`': 1,
  'tests/e2e/palette-controls.spec.ts › `${path}, ${theme}: every control it paints uses a palette colour`': 1,
  'tests/e2e/print-legibility.spec.ts › `${path}, ${saved ? `${saved} saved over a ${device} device` : `a ${device} device`}: every printed ink is readable on white paper`': 1,
  'tests/e2e/print-legibility.spec.ts › `${theme}: a disabled control never depends on its fill reaching paper`': 1,
  'tests/e2e/recorders.ts › expectNoUncaught': 1,
  'tests/e2e/recorders.ts › expectNone': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no sentence loses a space`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no two words are rendered touching`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no unfilled [[placeholder]] reaches the page`': 1,
  'tests/e2e/report-completeness.spec.ts › `${pagePath(pageId, locale)}: every catalogue string on the page is reportable there`': 1,
  'tests/e2e/report-form.spec.ts › `${locale}: every control is at least 44px, every text meets AA, every field has a 3:1 boundary`': 1,
  'tests/e2e/report-presence.spec.ts › a built page with a footer carries the form exactly when its locale is beta': 1,
  'tests/e2e/text-over-ribbon.spec.ts › `${theme} at ${width}px: every text run over the ribbon clears AA -- ${path}`': 1,
  'tests/e2e/thai-typography.spec.ts › `no Thai glyph draws beyond its line box -- ${route} at ${width}px, ${theme}`': 1,
  'tests/e2e/theme-script.spec.ts › `${path}: runs it before the first paint: inline, classic, in <head>, ahead of every stylesheet`': 1,
  'tests/e2e/theme.spec.ts › `${path} at ${width}px: no element moves between dark and light`': 1,
  'tests/e2e/visual.spec.ts › expectSamePixels': 1,
  'tests/e2e/zoom-on-focus.spec.ts › `${path}: every typed field computes to at least ${IOS_ZOOM_FLOOR_PX}px`': 1,
  'tests/product-links.ts › expectHomepageLinksAt': 1,
  'tests/unit/stranded-docblocks.test.ts › finds a docblock in every kind of source that holds one': 1,
  'tests/unit/stranded-docblocks.test.ts › finds none sitting directly on another': 1,
  'tests/unit/stranded-docblocks.test.ts › reads every source file git tracks': 1,
  'tests/unit/supply-chain.test.ts › a sub-path group is declared before the catch-all that would swallow it': 1,
  'tests/unit/supply-chain.test.ts › an action repo used at more than one sub-path is grouped into one PR': 1,
  'tests/unit/supply-chain.test.ts › builds every Dockerfile FROM a digest, beside the version it names': 1,
  'tests/unit/supply-chain.test.ts › every pinned action names the version its SHA resolves to': 1,
  'tests/unit/supply-chain.test.ts › every third-party action is pinned to a full commit SHA': 1,
  'tests/unit/supply-chain.test.ts › has Dependabot watching every directory that holds a Dockerfile': 1,
  'tests/unit/supply-chain.test.ts › is judged again once @astrojs/check accepts TypeScript 7': 1,
  "tests/unit/temporary-files.test.ts › passes over the run marker and the tools' own caches, each as measured": 1,
  'tests/unit/typecheck-scope.test.ts › no script opts itself out with a ts-nocheck directive': 1,
  'tests/unit/typed-fields.test.ts › is spelled in exactly one place under tests/': 1,
  'tests/unit/typed-fields.test.ts › still names every kind of field once serialised': 1,
  "tests/unit/verified-labels.test.ts › every one is pinned or awaiting the operator's read": 1,
  'tests/unit/verified-labels.test.ts › the pin covers every locale and every roster column, with nothing blank': 2,
  'tests/unit/waiting-reports-script.test.ts › expectNothingReceived': 1,
  'tests/unit/workflow-jobs.test.ts › leaves a graph with no conditional job alone': 1,
  'tests/unit/workflow-jobs.test.ts › passes a job calling a workflow in this repository, whose own jobs carry the budgets': 1,
  'tests/unit/workflow-jobs.test.ts › passes the condition deploy-dev.yml ships, judged over a live population': 1,
  'tests/unit/workflow-jobs.test.ts › passes whole minutes from 1 to 359, judged over a live population': 1,
};
