/**
 * Every `searched` site whose test checks no floor on the population it
 * searched, by `file › test title as written` (or function name), with how
 * many such sites that scope holds (#515). Measured by `searchSitesIn` when
 * the meta-guard landed (274 sites in 263 scopes) and again when #534 bound
 * each floor to its search's own population: 290 sites in 274 scopes.
 *
 * It may only shrink. A converted site makes its count too high, and
 * `floorless-searches.test.ts` is red until the count is lowered or the
 * entry removed; a new floorless site is red because it is not listed.
 */
export const FLOORLESS: Readonly<Record<string, number>> = {
  'tests/device/ios/journeys.journey.ts › `Journey 14 -- iOS-only, ${shape.what}: ${shape.count} pupils in ${shape.size}s on the projector board, with the fullscreen grant refused by the phone itself`': 1,
  'tests/e2e/baseurl-guard.spec.ts › every baseURL-aware API call on a relative URL is one the device fixtures actually resolve': 1,
  'tests/e2e/chrome.spec.ts › `${locale}: the footer names no company, and still reaches a person`': 1,
  'tests/e2e/classroom-groups-controls.spec.ts › `no horizontal scroll at ${width}px with any single section open — ${path}, every section derived`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › `every row still declares its own absence after ${what}`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding absent pupils removes the Absent column and only that column': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding the letters removes Sex, Together and Apart, and only those': 1,
  'tests/e2e/classroom-groups-print.spec.ts › showing absent pupils prints every column, including Absent': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › `${path}: no control holding typed text is submittable`': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › and nothing about them is written to storage': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › submitting cannot put a class list in the URL': 1,
  'tests/e2e/classroom-groups-projector.spec.ts › expectNothingOutOfReach': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `every roster control meets the 44px touch target with a placeholder showing -- ${path}`': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `no dropdown ever truncates its own column name -- ${path} at ${width}px`': 1,
  'tests/e2e/copy-reaches-a-page.spec.ts › `${locale}: no defined copy renders nowhere`': 3,
  'tests/e2e/copy-reaches-a-page.spec.ts › every page in every locale': 1,
  'tests/e2e/disabled-controls.spec.ts › `${theme}: the disabled placeholder option is excluded deliberately, and it exists`': 1,
  'tests/e2e/disabled-controls.spec.ts › `at 320px every disabled control keeps a 44px target, and the page does not scroll sideways -- ${path}`': 1,
  'tests/e2e/disabled-controls.spec.ts › default state — every disabled control shows the no-entry cursor': 1,
  'tests/e2e/disabled-controls.spec.ts › expectAReasonWithoutHover': 1,
  'tests/e2e/disabled-controls.spec.ts › expectDisabledPaint': 1,
  'tests/e2e/disabled-controls.spec.ts › expectNoEntryCursor': 1,
  'tests/e2e/disabled-controls.spec.ts › only checkbox, radio and file inputs are left to the UA to paint': 1,
  'tests/e2e/disabled-controls.spec.ts › the no-entry cursor marks the disabled controls apart from the enabled ones': 1,
  'tests/e2e/header-room.spec.ts › expectRoom': 2,
  "tests/e2e/locale-beta.spec.ts › `${locale}: the badge's spoken label keeps the page's language, even inside another language's entry`": 1,
  'tests/e2e/not-found-report.spec.ts › `${locale}: every control is at least 44px and every text meets AA`': 1,
  'tests/e2e/palette-controls.spec.ts › `${path}, ${theme}: every control it paints uses a palette colour`': 1,
  'tests/e2e/print-legibility.spec.ts › `${path}, ${saved ? `${saved} saved over a ${device} device` : `a ${device} device`}: every printed ink is readable on white paper`': 1,
  'tests/e2e/print-legibility.spec.ts › `${theme}: a disabled control never depends on its fill reaching paper`': 1,
  'tests/e2e/recorders.ts › expectNoUncaught': 1,
  'tests/e2e/recorders.ts › expectNone': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no sentence loses a space`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no two words are rendered touching`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no unfilled [[placeholder]] reaches the page`': 1,
  'tests/e2e/report-completeness.spec.ts › `${pagePath(pageId, locale)}: every catalogue string on the page is reportable there`': 1,
  'tests/e2e/report-form.spec.ts › `${locale}: every control is at least 44px, every text meets AA, every field has a 3:1 boundary`': 1,
  'tests/e2e/report-presence.spec.ts › a built page with a footer carries the form exactly when its locale is beta': 1,
  'tests/e2e/text-over-ribbon.spec.ts › `${theme} at ${width}px: every text run over the ribbon clears AA -- ${path}`': 1,
  'tests/e2e/thai-typography.spec.ts › `no Thai glyph draws beyond its line box -- ${route} at ${width}px, ${theme}`': 1,
  'tests/e2e/theme-script.spec.ts › `${path}: runs it before the first paint: inline, classic, in <head>, ahead of every stylesheet`': 1,
  'tests/e2e/theme.spec.ts › `${path} at ${width}px: no element moves between dark and light`': 1,
  'tests/e2e/visual.spec.ts › expectSamePixels': 1,
  'tests/e2e/zoom-on-focus.spec.ts › `${path}: every typed field computes to at least ${IOS_ZOOM_FLOOR_PX}px`': 1,
  'tests/product-links.ts › expectHomepageLinksAt': 1,
  'tests/unit/absence-liveness.test.ts › finds none whose population could be empty without saying so': 1,
  'tests/unit/absence-liveness.test.ts › reads as many absences in each file as its text writes': 1,
  'tests/unit/absence-liveness.test.ts › reads as text every spelling the reader reads, and no inverse': 2,
  'tests/unit/absence-liveness.test.ts › walks every .ts file git has under tests/': 1,
  'tests/unit/anchored-presence.test.ts › finds none reading raw source with an unanchored matcher': 1,
  'tests/unit/anchored-presence.test.ts › scans, in each file, the presence its text writes over raw file text': 1,
  'tests/unit/anchored-presence.test.ts › walks every .ts file git has under tests/': 1,
  'tests/unit/astro-css-strip.test.ts › scans no comment that the per-style read removes': 1,
  'tests/unit/back-translate.test.ts › fails loudly without an engine, before writing or sending anything': 1,
  'tests/unit/back-translate.test.ts › reads every locale back into English and writes the review': 1,
  'tests/unit/back-translate.test.ts › refuses an engine that cannot read a locale, before sending anything': 1,
  'tests/unit/board-geometry.test.ts › is spelled in exactly one place under tests/': 1,
  'tests/unit/board-geometry.test.ts › still names the things it measures once serialised': 1,
  'tests/unit/browser-matrix.test.ts › claims no spec that compares against a stored snapshot': 1,
  'tests/unit/browser-matrix.test.ts › holds only specs whose verdict cannot depend on the engine or viewport': 1,
  'tests/unit/browser-matrix.test.ts › is excluded from every OTHER project': 1,
  'tests/unit/browser-matrix.test.ts › lets no device project claim the visual suite': 1,
  'tests/unit/browser-matrix.test.ts › names specs that actually exist': 1,
  'tests/unit/browser-matrix.test.ts › passes no --retries but 0 in any workflow step or package script': 1,
  'tests/unit/browser-matrix.test.ts › refuses test.only under CI, in every Playwright config': 1,
  'tests/unit/browser-matrix.test.ts › resolves retries to 0 in every Playwright config and project, under CI': 1,
  'tests/unit/browser-matrix.test.ts › runs every resolved project light or dark, never the default': 1,
  'tests/unit/browser-matrix.test.ts › still runs every other e2e spec on the phone, content-only ones included': 1,
  'tests/unit/cli-only.test.ts › is imported by nothing the site ships': 1,
  'tests/unit/closes-over-nothing.ts › expectClosesOverNothing': 1,
  'tests/unit/closing-keywords.test.ts › leaves every safe phrasing alone': 1,
  'tests/unit/closing-keywords.test.ts › never expands the body into a shell command': 1,
  'tests/unit/collection-needs-no-build.test.ts › no file under tests/ reads dist/ while the suite is collected': 1,
  'tests/unit/colour-literals.test.ts › allows nothing the reader cannot find': 1,
  'tests/unit/colour-literals.test.ts › reads CSS by rule and skips paper, and reads code whole': 1,
  'tests/unit/colour-literals.test.ts › writes no colour literal outside tokens.css but the allowed ones': 1,
  'tests/unit/contrast.test.ts › `${theme}: every colour token is classified — paired or explicitly decorative`': 1,
  'tests/unit/contrast.test.ts › `${theme}: every declared pair clears its required ratio, over the worst subset of the atmosphere`': 1,
  'tests/unit/contrast.test.ts › `${theme}: pins the disabled fill, and keeps it off every ground it is drawn on`': 1,
  'tests/unit/contrast.test.ts › calls a border decorative only where the reader finds one': 1,
  'tests/unit/contrast.test.ts › every --border usage is classified as control or decorative': 1,
  'tests/unit/contrast.test.ts › names a control only where the reader finds that selector': 1,
  'tests/unit/contrast.test.ts › no component paints a disabled control for itself': 1,
  'tests/unit/contrast.test.ts › no control selector draws its boundary with --border': 1,
  'tests/unit/csv.test.ts › correcting the sex header moved nothing else, in any locale': 1,
  'tests/unit/csv.test.ts › every locale survives an export/import round trip with sex intact': 1,
  'tests/unit/csv.test.ts › gives no token two different meanings across locales': 1,
  'tests/unit/csv.test.ts › shares no header word between any two locales': 1,
  "tests/unit/csv.test.ts › the class comment names the class the way the page's own field does": 1,
  'tests/unit/csv.test.ts › the sex header agrees with the roster column the teacher sees': 1,
  'tests/unit/csv.test.ts › the sex tokens are the letters the roster offers the teacher': 1,
  'tests/unit/csv.test.ts › writes an empty cell for sex, together and apart in every locale': 1,
  'tests/unit/custom-properties.test.ts › every var() in src names a property src defines': 1,
  'tests/unit/dashboard-paths.test.ts › spells each shared path in the harness, and only there': 1,
  'tests/unit/dead-copy.test.ts › every error code the copy defines is rendered by renderError': 1,
  'tests/unit/dead-copy.test.ts › every warning code the copy defines is rendered by renderWarning': 1,
  'tests/unit/dead-copy.test.ts › the site-wide copy defines nothing that no page renders': 1,
  'tests/unit/dead-copy.test.ts › the tool locale defines nothing that no page renders': 1,
  'tests/unit/dependabot-labels.test.ts › `runs inside ${REQUIRED_JOB} or a job it stands for, the context branch protection requires`': 1,
  'tests/unit/dependabot-labels.test.ts › come from the parsed document, so a comment cannot add one': 1,
  'tests/unit/deprecated-css.test.ts › finds none in any stylesheet under src/': 1,
  'tests/unit/deprecated-css.test.ts › reads every declaration the stylesheets hold, and as many as there are': 1,
  'tests/unit/device-tool-homes.test.ts › only scripts/adb.mjs decides which listed device is ready': 1,
  'tests/unit/device-tool-homes.test.ts › reads every call site through the one home': 1,
  'tests/unit/duplicate-imports.test.ts › reads every import the sources declare, and as many as there are': 1,
  'tests/unit/duplicate-imports.test.ts › src, scripts and tests each import a module once': 1,
  'tests/unit/duplication.test.ts › carries no verdict for a pair that no longer exists': 1,
  'tests/unit/duplication.test.ts › finds no cross-file duplicate that has not been given a verdict': 1,
  'tests/unit/duplication.test.ts › records each verdict against one pair, which no copy can inherit': 1,
  'tests/unit/event-collectors.test.ts › every .all() loop proves its locator is not empty first': 1,
  'tests/unit/event-collectors.test.ts › follows every .all() list it meets into a loop it can judge': 1,
  'tests/unit/event-collectors.test.ts › reads as many .all() calls as the text holds, file by file': 1,
  'tests/unit/event-collectors.test.ts › scans every file git has in a directory that holds a spec': 1,
  'tests/unit/evidence-page.test.ts › emits only media references the artifact serves': 1,
  'tests/unit/evidence-page.test.ts › has no consumer spelling an evidence filename for itself': 1,
  'tests/unit/evidence-page.test.ts › never deletes a directory the operator was asked to keep': 1,
  'tests/unit/evidence-page.test.ts › references every recording it was given': 1,
  'tests/unit/evidence-recording.test.ts › every construct in the vocabulary is detectable': 3,
  'tests/unit/evidence-recording.test.ts › every spec that acts declares test.use(recorded)': 1,
  'tests/unit/evidence-recording.test.ts › keeps video in one home: no spec spells it itself': 1,
  'tests/unit/evidence-recording.test.ts › no journey in a recording spec records blank frames (#292)': 1,
  'tests/unit/evidence-recording.test.ts › no spec declares test.use(recorded) without acting': 1,
  'tests/unit/excluded-by-design.test.ts › never spells a --grep pattern out as a literal again': 1,
  'tests/unit/feature-terms.test.ts › %s: every approved word is in use, so none is a typo or a stale approval': 1,
  'tests/unit/feature-terms.test.ts › %s: every piece of copy that names a feature carries an approved word for it': 1,
  'tests/unit/floors.test.ts › reads the recorded figures as whole numbers keyed by id': 1,
  'tests/unit/git-env.test.ts › are unset before any test file runs': 1,
  'tests/unit/gloryPoints.test.ts › no translated site catalogue reuses one of English’s functions': 1,
  'tests/unit/grouping.test.ts › spreads the girls across different groups even when the numbers do not divide evenly': 1,
  'tests/unit/home-copy.test.ts › `${locale}: no homepage string calls a product first or the flagship`': 1,
  'tests/unit/i18n.test.ts › Indonesian is actually translated, not copied English': 1,
  'tests/unit/i18n.test.ts › no site string is blank in either language': 1,
  'tests/unit/i18n.test.ts › the visible prose is genuinely translated, not copied English': 1,
  'tests/unit/install-scripts.test.ts › approves rather than denies — a false value blocks the install': 1,
  'tests/unit/install-scripts.test.ts › pins every approval to a version': 1,
  'tests/unit/label-check.test.ts › %s: every sentence that names a label carries that label': 1,
  'tests/unit/literal-floors.test.ts › counts every floor matcher the code writes, file by file': 1,
  'tests/unit/literal-floors.test.ts › finds none written as a literal or handed in by a parameter': 1,
  'tests/unit/literal-floors.test.ts › lists no product value or Group 5 floor that is gone': 1,
  'tests/unit/literal-floors.test.ts › reads every TypeScript file git has under tests/': 1,
  'tests/unit/literal-floors.test.ts › spells every recorded id exactly once under tests/': 1,
  'tests/unit/literal-grounds.test.ts › every literal ground under src/ paints a literal ink, or is exempt with its reason': 1,
  'tests/unit/literal-grounds.test.ts › exempts only grounds the reader finds': 1,
  'tests/unit/literal-grounds.test.ts › joins a selector split over several rules, keeping the last of each property': 2,
  'tests/unit/literal-grounds.test.ts › leaves alone what carries its own ground, what is not inside, and paper': 1,
  'tests/unit/literal-grounds.test.ts › no rule under src/ puts token ink on text inside a literal ground': 1,
  'tests/unit/literal-grounds.test.ts › reads a token with a literal fallback as a token, on the ground and on the ink': 1,
  'tests/unit/locale-fallbacks.test.ts › `${locale}: has no empty or whitespace-only copy`': 1,
  'tests/unit/locale-fallbacks.test.ts › `${locale}: no message is still English`': 1,
  'tests/unit/locale-metadata.test.ts › covers every locale that is actually routed': 1,
  'tests/unit/locale-metadata.test.ts › covers every routed locale': 1,
  'tests/unit/message-parity.test.ts › %s fills the slots English fills, in every string': 1,
  'tests/unit/message-parity.test.ts › %s offers every choice of sentence English offers': 1,
  'tests/unit/message-parity.test.ts › %s takes nothing from English but its type': 1,
  'tests/unit/message-parity.test.ts › every plural offers exactly the forms its language has': 1,
  'tests/unit/no-dated-render.test.ts › is not tripped by a date named in a comment': 1,
  'tests/unit/no-dated-render.test.ts › no .astro source reads the date, in its code or its markup': 1,
  'tests/unit/no-dated-render.test.ts › reads every view the sources hold, and as many as there are': 2,
  'tests/unit/one-test-per-case.test.ts › loops no known population inside a test': 1,
  'tests/unit/one-test-per-case.test.ts › reads the tests every spec declares, and as many as there are': 3,
  'tests/unit/organisation-name.test.ts › only the one historic fixture outside the dated docs': 1,
  'tests/unit/pipeline-wiring.test.ts › a Cloudflare secret is read only in the environment of what its job does (#241, #349)': 1,
  'tests/unit/pipeline-wiring.test.ts › can go red: nothing in it continues on error': 1,
  'tests/unit/pipeline-wiring.test.ts › clears every per-group report before a run, now that nothing wipes them': 1,
  'tests/unit/pipeline-wiring.test.ts › documents only a context something in this repository can report': 1,
  'tests/unit/pipeline-wiring.test.ts › every artifact capture states what an empty capture means': 1,
  'tests/unit/pipeline-wiring.test.ts › every astro server script opts out of the agent auto-background': 1,
  'tests/unit/pipeline-wiring.test.ts › every deploy runs the locked copy': 1,
  'tests/unit/pipeline-wiring.test.ts › every job running the e2e suite carries exactly the shard budget': 1,
  'tests/unit/pipeline-wiring.test.ts › every job that reads a secret other than GITHUB_TOKEN names an environment (#241)': 1,
  'tests/unit/pipeline-wiring.test.ts › every upload in a matrix job names its leg': 1,
  'tests/unit/pipeline-wiring.test.ts › every workflow states a workflow-level permissions block': 1,
  'tests/unit/pipeline-wiring.test.ts › is not bypassed by any workflow calling Playwright directly': 1,
  'tests/unit/pipeline-wiring.test.ts › jobBlockRunning': 1,
  'tests/unit/pipeline-wiring.test.ts › lets a fallback test the status of the command producing its text': 1,
  'tests/unit/pipeline-wiring.test.ts › lets the script name the engine from its Dockerfile': 1,
  'tests/unit/pipeline-wiring.test.ts › nests none inside another, which a parent wipe would take with it': 1,
  'tests/unit/pipeline-wiring.test.ts › never calls a deploy a release': 1,
  'tests/unit/pipeline-wiring.test.ts › no artifact capture in any workflow is set to ignore': 1,
  'tests/unit/pipeline-wiring.test.ts › no checkout in any workflow leaves the job token in .git/config (#395)': 1,
  'tests/unit/pipeline-wiring.test.ts › no job in any workflow is silently skipped by a skip upstream of it (#157)': 1,
  'tests/unit/pipeline-wiring.test.ts › no job in any workflow runs on the runner default budget': 1,
  'tests/unit/pipeline-wiring.test.ts › no job running the e2e suite builds the site before it': 1,
  'tests/unit/pipeline-wiring.test.ts › no job that deploys or verifies prod reads a secret meant for dev (#241)': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow a pull request can start grants a write scope to a silent job': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow installs it globally': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow names a workflow file that does not exist': 1,
  'tests/unit/pipeline-wiring.test.ts › only the waiting-reports count reads secrets in reports-count, or its token anywhere (#349)': 1,
  'tests/unit/pipeline-wiring.test.ts › pins an image rather than a label that migrates under it': 1,
  'tests/unit/pipeline-wiring.test.ts › prints the container architecture into the job summary': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every job running the suite, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every workflow file reference, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every workflow for an install, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › runs every other Playwright job in the image the `image` job picks': 1,
  'tests/unit/pipeline-wiring.test.ts › runs neither npm run floors:record nor its script': 1,
  'tests/unit/pipeline-wiring.test.ts › takes the image the baselines are captured in from one selector': 1,
  'tests/unit/pipeline-wiring.test.ts › the dispatch path grants the workflow it calls every permission its jobs ask for': 1,
  'tests/unit/pipeline-wiring.test.ts › uploads the gate diff and the measurement diff together (#311)': 1,
  'tests/unit/playwright-declarations.test.ts › counts every way a spec writes a test': 1,
  'tests/unit/playwright-declarations.test.ts › counts nothing that is not a test': 1,
  'tests/unit/playwright-declarations.test.ts › no tag or use option is written in a form the guards would misread': 1,
  'tests/unit/playwright-declarations.test.ts › the only shared options object is the recording opt-in, from its home': 1,
  'tests/unit/release-inventory.test.ts › can see every capture: no module but a spec calls shoot': 1,
  'tests/unit/release-prose.test.ts › finds none of any release file’s sentences in the scripts that render it': 1,
  'tests/unit/report-review.test.ts › makes none, and says so per report, without BACK_TRANSLATE_URL': 1,
  'tests/unit/report-review.test.ts › never calls the engine when no report needs it': 1,
  'tests/unit/route-coverage.test.ts › hardcodes no locale-prefixed route in any deploy gate': 1,
  'tests/unit/route-coverage.test.ts › reads every locale-prefixed string the parse tree holds': 1,
  'tests/unit/sanity-on-build.test.ts › `runs at least one test from every spec file in ${testDir}`': 1,
  'tests/unit/sanity-on-build.test.ts › are left out of the on-build run, and nothing else is': 1,
  'tests/unit/sanity-on-build.test.ts › each says, where it is written, why only the deployed site can answer it': 1,
  'tests/unit/scoped-classes.test.ts › can read every class those files write': 1,
  'tests/unit/scoped-classes.test.ts › holds for every .astro file under src/': 1,
  'tests/unit/scratch-git-home.test.ts › no call anywhere else hands git a cwd': 1,
  'tests/unit/script-entry.test.ts › decides on import.meta.main alone': 1,
  'tests/unit/script-entry.test.ts › judges every load-time statement the scripts hold, and as many as there are': 1,
  'tests/unit/script-entry.test.ts › judges every read of process.argv the scripts make, and as many as there are': 1,
  'tests/unit/script-entry.test.ts › leaves every effect to an import.meta.main decision': 1,
  'tests/unit/script-entry.test.ts › never reads process.argv[1]': 1,
  'tests/unit/script-entry.test.ts › reads every file under scripts/': 1,
  'tests/unit/shipped-defaults.test.ts › refuses an expectation a roster-building test could not have written': 1,
  'tests/unit/shytalk-brand.test.ts › is spelled out nowhere else in the repo': 1,
  'tests/unit/shytalk-brand.test.ts › reads every source file, and as many as there are': 1,
  'tests/unit/shytalk-showcase.test.ts › authors every capture at exactly the 2x frame size, and no larger': 1,
  'tests/unit/shytalk-showcase.test.ts › gives every locale its OWN capture, not one file under five names': 1,
  'tests/unit/shytalk-showcase.test.ts › has a capture for every locale the site serves': 1,
  'tests/unit/shytalk-showcase.test.ts › keeps every capture inside the per-visit weight budget': 1,
  'tests/unit/shytalk-showcase.test.ts › stores every capture as a PNG, so the size read above is meaningful': 1,
  'tests/unit/source-files.test.ts › accepts a plain count, which cannot be content-checked': 2,
  'tests/unit/source-files.test.ts › accepts a population where only SOME members carry content': 1,
  'tests/unit/source-files.test.ts › counts a zero and a false as content -- they are values, not blanks': 2,
  'tests/unit/source-files.test.ts › holds every file git tracks': 1,
  'tests/unit/source-files.test.ts › names the population in the message, so a failure says what died': 1,
  'tests/unit/source-files.test.ts › refuses a population of BLANK strings -- #112 exactly': 1,
  'tests/unit/source-files.test.ts › refuses a population of empty containers': 1,
  'tests/unit/source-files.test.ts › refuses a population of null and undefined': 1,
  'tests/unit/source-files.test.ts › refuses a population that is empty': 1,
  'tests/unit/source-files.test.ts › returns the findings untouched, so the caller still owns the verdict': 1,
  'tests/unit/source-files.test.ts › skips dotfiles and node_modules, which only four of the nine did': 2,
  'tests/unit/spec-scan.ts › expectNothingFound': 3,
  'tests/unit/stranded-docblocks.test.ts › finds a docblock in every kind of source that holds one': 1,
  'tests/unit/stranded-docblocks.test.ts › finds none sitting directly on another': 1,
  'tests/unit/stranded-docblocks.test.ts › reads every source file git tracks': 1,
  'tests/unit/supply-chain.test.ts › a sub-path group is declared before the catch-all that would swallow it': 1,
  'tests/unit/supply-chain.test.ts › an action repo used at more than one sub-path is grouped into one PR': 1,
  'tests/unit/supply-chain.test.ts › builds every Dockerfile FROM a digest, beside the version it names': 1,
  'tests/unit/supply-chain.test.ts › every pinned action names the version its SHA resolves to': 1,
  'tests/unit/supply-chain.test.ts › every third-party action is pinned to a full commit SHA': 1,
  'tests/unit/supply-chain.test.ts › has Dependabot watching every directory that holds a Dockerfile': 1,
  'tests/unit/supply-chain.test.ts › is judged again once @astrojs/check accepts TypeScript 7': 1,
  "tests/unit/temporary-files.test.ts › passes over the run marker and the tools' own caches, each as measured": 1,
  'tests/unit/tokens.test.ts › declares color-scheme only beside a palette': 1,
  'tests/unit/tokens.test.ts › declares no token that nothing reads': 1,
  'tests/unit/tokens.test.ts › declares the same tokens, with the same values, in every dark block': 1,
  'tests/unit/tokens.test.ts › defines no token only inside a dark block': 1,
  'tests/unit/tokens.test.ts › keeps every dark block screen-only, and has both states it needs': 1,
  'tests/unit/tracked-paths.test.ts › every tracked path is made of plain names': 1,
  'tests/unit/translate-messages.test.ts › loads every module a script imports from src/': 1,
  'tests/unit/translate-messages.test.ts › sends no syntax for any real English message': 1,
  'tests/unit/translate.test.ts › drops the stale drafts as --send writes, even with nothing to send': 1,
  'tests/unit/translate.test.ts › drops the stale drafts with --prune, with no key and no request': 1,
  'tests/unit/translate.test.ts › holds no draft in the committed cache for English the harness does not send': 1,
  'tests/unit/translate.test.ts › reports the stale drafts on a dry run and writes nothing': 1,
  'tests/unit/translate.test.ts › round-trips every real catalogue string through the whole pipeline': 1,
  'tests/unit/typecheck-scope.test.ts › no script opts itself out with a ts-nocheck directive': 1,
  'tests/unit/typed-fields.test.ts › is spelled in exactly one place under tests/': 1,
  'tests/unit/typed-fields.test.ts › still names every kind of field once serialised': 1,
  "tests/unit/verified-labels.test.ts › every one is pinned or awaiting the operator's read": 1,
  'tests/unit/verified-labels.test.ts › the pin covers every locale and every roster column, with nothing blank': 2,
  'tests/unit/waiting-reports-script.test.ts › expectNothingReceived': 1,
  'tests/unit/workflow-jobs.test.ts › leaves a graph with no conditional job alone': 1,
  'tests/unit/workflow-jobs.test.ts › passes a job calling a workflow in this repository, whose own jobs carry the budgets': 1,
  'tests/unit/workflow-jobs.test.ts › passes the condition deploy-dev.yml ships, judged over a live population': 1,
  'tests/unit/workflow-jobs.test.ts › passes whole minutes from 1 to 359, judged over a live population': 1,
};
