/**
 * Every `searched` site whose test checks no floor on the population it
 * searched, by `file › test title as written` (or function name), with how
 * many such sites that scope holds (#515). Measured by `searchSitesIn` when
 * the meta-guard landed (274 sites in 263 scopes) and again when #534 bound
 * each floor to its search's own population: 290 sites in 274 scopes.
 *
 * It may only shrink. A converted site makes its count too high, and
 * `floorless-searches.test.ts` is red until the count is lowered or the
 * entry removed; a new floorless site is red because it is not listed.
 */
export const FLOORLESS: Readonly<Record<string, number>> = {
  'tests/device/ios/journeys.journey.ts › `Journey 14 -- iOS-only, ${shape.what}: ${shape.count} pupils in ${shape.size}s on the projector board, with the fullscreen grant refused by the phone itself`': 1,
  'tests/e2e/baseurl-guard.spec.ts › every baseURL-aware API call on a relative URL is one the device fixtures actually resolve': 1,
  'tests/e2e/chrome.spec.ts › `${locale}: the footer names no company, and still reaches a person`': 1,
  'tests/e2e/classroom-groups-controls.spec.ts › `no horizontal scroll at ${width}px with any single section open — ${path}, every section derived`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › `every row still declares its own absence after ${what}`': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding absent pupils removes the Absent column and only that column': 1,
  'tests/e2e/classroom-groups-print.spec.ts › hiding the letters removes Sex, Together and Apart, and only those': 1,
  'tests/e2e/classroom-groups-print.spec.ts › showing absent pupils prints every column, including Absent': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › `${path}: no control holding typed text is submittable`': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › and nothing about them is written to storage': 1,
  'tests/e2e/classroom-groups-privacy.spec.ts › submitting cannot put a class list in the URL': 1,
  'tests/e2e/classroom-groups-projector.spec.ts › expectNothingOutOfReach': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `every roster control meets the 44px touch target with a placeholder showing -- ${path}`': 1,
  'tests/e2e/classroom-groups-roster.spec.ts › `no dropdown ever truncates its own column name -- ${path} at ${width}px`': 1,
  'tests/e2e/copy-reaches-a-page.spec.ts › `${locale}: no defined copy renders nowhere`': 3,
  'tests/e2e/copy-reaches-a-page.spec.ts › every page in every locale': 1,
  'tests/e2e/disabled-controls.spec.ts › `${theme}: the disabled placeholder option is excluded deliberately, and it exists`': 1,
  'tests/e2e/disabled-controls.spec.ts › `at 320px every disabled control keeps a 44px target, and the page does not scroll sideways -- ${path}`': 1,
  'tests/e2e/disabled-controls.spec.ts › default state — every disabled control shows the no-entry cursor': 1,
  'tests/e2e/disabled-controls.spec.ts › expectAReasonWithoutHover': 1,
  'tests/e2e/disabled-controls.spec.ts › expectDisabledPaint': 1,
  'tests/e2e/disabled-controls.spec.ts › expectNoEntryCursor': 1,
  'tests/e2e/disabled-controls.spec.ts › only checkbox, radio and file inputs are left to the UA to paint': 1,
  'tests/e2e/disabled-controls.spec.ts › the no-entry cursor marks the disabled controls apart from the enabled ones': 1,
  'tests/e2e/header-room.spec.ts › expectRoom': 2,
  "tests/e2e/locale-beta.spec.ts › `${locale}: the badge's spoken label keeps the page's language, even inside another language's entry`": 1,
  'tests/e2e/not-found-report.spec.ts › `${locale}: every control is at least 44px and every text meets AA`': 1,
  'tests/e2e/palette-controls.spec.ts › `${path}, ${theme}: every control it paints uses a palette colour`': 1,
  'tests/e2e/print-legibility.spec.ts › `${path}, ${saved ? `${saved} saved over a ${device} device` : `a ${device} device`}: every printed ink is readable on white paper`': 1,
  'tests/e2e/print-legibility.spec.ts › `${theme}: a disabled control never depends on its fill reaching paper`': 1,
  'tests/e2e/recorders.ts › expectNoUncaught': 1,
  'tests/e2e/recorders.ts › expectNone': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no sentence loses a space`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no two words are rendered touching`': 1,
  'tests/e2e/rendered-text.spec.ts › `${path}: no unfilled [[placeholder]] reaches the page`': 1,
  'tests/e2e/report-completeness.spec.ts › `${pagePath(pageId, locale)}: every catalogue string on the page is reportable there`': 1,
  'tests/e2e/report-form.spec.ts › `${locale}: every control is at least 44px, every text meets AA, every field has a 3:1 boundary`': 1,
  'tests/e2e/report-presence.spec.ts › a built page with a footer carries the form exactly when its locale is beta': 1,
  'tests/e2e/text-over-ribbon.spec.ts › `${theme} at ${width}px: every text run over the ribbon clears AA -- ${path}`': 1,
  'tests/e2e/thai-typography.spec.ts › `no Thai glyph draws beyond its line box -- ${route} at ${width}px, ${theme}`': 1,
  'tests/e2e/theme-script.spec.ts › `${path}: runs it before the first paint: inline, classic, in <head>, ahead of every stylesheet`': 1,
  'tests/e2e/theme.spec.ts › `${path} at ${width}px: no element moves between dark and light`': 1,
  'tests/e2e/visual.spec.ts › expectSamePixels': 1,
  'tests/e2e/zoom-on-focus.spec.ts › `${path}: every typed field computes to at least ${IOS_ZOOM_FLOOR_PX}px`': 1,
  'tests/product-links.ts › expectHomepageLinksAt': 1,
  'tests/unit/deprecated-css.test.ts › reads every declaration the stylesheets hold, and as many as there are': 1,
  'tests/unit/duplicate-imports.test.ts › reads every import the sources declare, and as many as there are': 1,
  'tests/unit/excluded-by-design.test.ts › never spells a --grep pattern out as a literal again': 1,
  'tests/unit/literal-grounds.test.ts › every literal ground under src/ paints a literal ink, or is exempt with its reason': 1,
  'tests/unit/literal-grounds.test.ts › exempts only grounds the reader finds': 1,
  'tests/unit/literal-grounds.test.ts › joins a selector split over several rules, keeping the last of each property': 2,
  'tests/unit/literal-grounds.test.ts › leaves alone what carries its own ground, what is not inside, and paper': 1,
  'tests/unit/literal-grounds.test.ts › no rule under src/ puts token ink on text inside a literal ground': 1,
  'tests/unit/literal-grounds.test.ts › reads a token with a literal fallback as a token, on the ground and on the ink': 1,
  'tests/unit/locale-fallbacks.test.ts › `${locale}: has no empty or whitespace-only copy`': 1,
  'tests/unit/locale-fallbacks.test.ts › `${locale}: no message is still English`': 1,
  'tests/unit/locale-metadata.test.ts › covers every locale that is actually routed': 1,
  'tests/unit/locale-metadata.test.ts › covers every routed locale': 1,
  'tests/unit/message-parity.test.ts › %s fills the slots English fills, in every string': 1,
  'tests/unit/message-parity.test.ts › %s offers every choice of sentence English offers': 1,
  'tests/unit/message-parity.test.ts › %s takes nothing from English but its type': 1,
  'tests/unit/message-parity.test.ts › every plural offers exactly the forms its language has': 1,
  'tests/unit/no-dated-render.test.ts › is not tripped by a date named in a comment': 1,
  'tests/unit/no-dated-render.test.ts › no .astro source reads the date, in its code or its markup': 1,
  'tests/unit/no-dated-render.test.ts › reads every view the sources hold, and as many as there are': 2,
  'tests/unit/one-test-per-case.test.ts › loops no known population inside a test': 1,
  'tests/unit/one-test-per-case.test.ts › reads the tests every spec declares, and as many as there are': 3,
  'tests/unit/pipeline-wiring.test.ts › no checkout in any workflow leaves the job token in .git/config (#395)': 1,
  'tests/unit/pipeline-wiring.test.ts › no job in any workflow is silently skipped by a skip upstream of it (#157)': 1,
  'tests/unit/pipeline-wiring.test.ts › no job in any workflow runs on the runner default budget': 1,
  'tests/unit/pipeline-wiring.test.ts › no job running the e2e suite builds the site before it': 1,
  'tests/unit/pipeline-wiring.test.ts › no job that deploys or verifies prod reads a secret meant for dev (#241)': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow a pull request can start grants a write scope to a silent job': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow installs it globally': 1,
  'tests/unit/pipeline-wiring.test.ts › no workflow names a workflow file that does not exist': 1,
  'tests/unit/pipeline-wiring.test.ts › only the waiting-reports count reads secrets in reports-count, or its token anywhere (#349)': 1,
  'tests/unit/pipeline-wiring.test.ts › pins an image rather than a label that migrates under it': 1,
  'tests/unit/pipeline-wiring.test.ts › prints the container architecture into the job summary': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every job running the suite, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every workflow file reference, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › reads every workflow for an install, and as many as there are': 1,
  'tests/unit/pipeline-wiring.test.ts › runs every other Playwright job in the image the `image` job picks': 1,
  'tests/unit/pipeline-wiring.test.ts › runs neither npm run floors:record nor its script': 1,
  'tests/unit/pipeline-wiring.test.ts › takes the image the baselines are captured in from one selector': 1,
  'tests/unit/pipeline-wiring.test.ts › the dispatch path grants the workflow it calls every permission its jobs ask for': 1,
  'tests/unit/pipeline-wiring.test.ts › uploads the gate diff and the measurement diff together (#311)': 1,
  'tests/unit/sanity-on-build.test.ts › `runs at least one test from every spec file in ${testDir}`': 1,
  'tests/unit/sanity-on-build.test.ts › are left out of the on-build run, and nothing else is': 1,
  'tests/unit/sanity-on-build.test.ts › each says, where it is written, why only the deployed site can answer it': 1,
  'tests/unit/scoped-classes.test.ts › can read every class those files write': 1,
  'tests/unit/scoped-classes.test.ts › holds for every .astro file under src/': 1,
  'tests/unit/scratch-git-home.test.ts › no call anywhere else hands git a cwd': 1,
  'tests/unit/script-entry.test.ts › decides on import.meta.main alone': 1,
  'tests/unit/script-entry.test.ts › judges every load-time statement the scripts hold, and as many as there are': 1,
  'tests/unit/script-entry.test.ts › judges every read of process.argv the scripts make, and as many as there are': 1,
  'tests/unit/script-entry.test.ts › leaves every effect to an import.meta.main decision': 1,
  'tests/unit/script-entry.test.ts › never reads process.argv[1]': 1,
  'tests/unit/script-entry.test.ts › reads every file under scripts/': 1,
  'tests/unit/shytalk-brand.test.ts › reads every source file, and as many as there are': 1,
  'tests/unit/spec-scan.ts › expectNothingFound': 3,
  'tests/unit/stranded-docblocks.test.ts › finds a docblock in every kind of source that holds one': 1,
  'tests/unit/stranded-docblocks.test.ts › finds none sitting directly on another': 1,
  'tests/unit/stranded-docblocks.test.ts › reads every source file git tracks': 1,
  'tests/unit/supply-chain.test.ts › a sub-path group is declared before the catch-all that would swallow it': 1,
  'tests/unit/supply-chain.test.ts › an action repo used at more than one sub-path is grouped into one PR': 1,
  'tests/unit/supply-chain.test.ts › builds every Dockerfile FROM a digest, beside the version it names': 1,
  'tests/unit/supply-chain.test.ts › every pinned action names the version its SHA resolves to': 1,
  'tests/unit/supply-chain.test.ts › every third-party action is pinned to a full commit SHA': 1,
  'tests/unit/supply-chain.test.ts › has Dependabot watching every directory that holds a Dockerfile': 1,
  'tests/unit/supply-chain.test.ts › is judged again once @astrojs/check accepts TypeScript 7': 1,
  "tests/unit/temporary-files.test.ts › passes over the run marker and the tools' own caches, each as measured": 1,
};
