import type { Catalogue } from './en';

/**
 * vi — generated by `scripts/i18n-scaffold.mjs` from en.ts and the DeepL
 * cache (#22), then REVIEWED BY HAND. Re-rendering discards those reviews, so
 * the generator refuses to overwrite this file without `--force`.
 *
 * Every message is a template rebuilt from DeepL's translation of the
 * sentences it can say, and checked to fill exactly the slots English fills
 * (#136).
 *
 * MACHINE-TRANSLATED COPY IS A FIRST DRAFT. It has been checked for structure
 * — placeholders intact, protected names preserved, nothing empty — and NOT
 * for fluency, which needs a speaker of this language.
 */
export const vi: Catalogue = {
  title: 'Trình tạo nhóm trong lớp học',
  description:
    'Chia lớp học của bạn thành các nhóm ngay lập tức — ngay trên trình duyệt, mà không cần gửi dữ liệu đi đâu cả.',
  heading: 'Trình tạo nhóm trong lớp học',
  lead: 'Được phát triển dành cho giáo viên, bởi Shyden. Việc chia lớp một cách công bằng tốn thời gian mà bạn không có, và nếu làm thủ công thì dễ dẫn đến tranh cãi về việc thiên vị. Công cụ này giúp bạn hoàn thành việc đó chỉ với một cú nhấp chuột — miễn phí, không cần đăng ký, và mọi thông tin về lớp học của bạn sẽ không bao giờ rời khỏi trình duyệt.',
  privacy:
    'Mọi thứ đều diễn ra ngay trong trình duyệt của bạn. Danh sách lớp học sẽ không bao giờ được chuyển ra khỏi trang này.',
  howToHeading: 'Cách sử dụng',
  howToWhat:
    'Hãy cho chương trình biết lớp của bạn có bao nhiêu học sinh và bạn muốn mỗi nhóm có bao nhiêu học sinh. Chương trình sẽ xáo trộn danh sách và phân chia học sinh vào các nhóm, đồng thời đảm bảo không có nhóm nào có số lượng học sinh ít hơn số lượng bạn yêu cầu.',
  howToSteps: [
    'Hãy cho biết trong lớp bạn có bao nhiêu học sinh.',
    'Hãy chọn cách chia nhóm cho các em.',
    'Nhấn vào “Tạo nhóm”.',
  ],
  classLabel: 'Lớp (tùy chọn)',
  studentsLabel: 'Số lượng học sinh',
  studentsHelp:
    'Các học sinh được giấu tên và đánh số — Học sinh 1, Học sinh 2, v.v.',
  studentsLockedReason:
    'Được thiết lập theo danh sách của bạn. Để thay đổi danh sách này, hãy thêm hoặc xóa học sinh trong phần “Thông tin học sinh”.',
  // #188. DeepL draft, awaiting a speaker (#53, #161). The three labels are
  // three words or fewer -- the exact class that produced `Tình dục` as a
  // column header on a pupil roster -- so a speaker must read them apart
  // from the surrounding prose, which machine translation gets right.
  absentNumbersLabel: 'Mã học sinh',
  keepTogetherLabel: 'Xếp cùng nhóm',
  keepApartLabel: 'Xếp khác nhóm',
  absentNumbersHelp:
    'Mã học sinh của những học sinh vắng mặt, phân tách bằng dấu phẩy.',
  pairNumbersHelp:
    'Dấu phẩy nối một cặp; dấu chấm phẩy bắt đầu cặp mới — 3,9; 14,15.',
  numbersLockedReason:
    'Được thiết lập theo danh sách của bạn. Hãy đánh dấu vắng mặt và ghép cặp trong phần “Thông tin học sinh” để thay đổi.',
  numbersNotWholeMessage:
    '“{text}” không phải là số nguyên. Hãy nhập số thứ tự từ 1 đến {count}.',
  numbersAboveCountMessage: 'Không có số {text}. Bạn có {count} học sinh.',
  numbersAboveMaximumMessage:
    'Không có số {text}. Trang này chỉ hỗ trợ tối đa {max} học sinh.',
  numbersDuplicateMessage:
    'Số {text} được liệt kê hai lần. Mỗi số chỉ thuộc về một chỗ.',
  numbersLonelySetMessage:
    'Một cặp cần ít nhất hai số, nhưng {text} chỉ có một mình.',
  numbersTooManySetsMessage:
    'Số cặp vượt quá khả năng của trang này. {text} là cặp dư ra.',
  numbersNoCountMessage: 'Hãy điền số lượng học sinh trước.',
  // No plural wrapper: Vietnamese has only the `other` category, the same
  // shape `rosterGapWarning` below already uses for its {missing} slot.
  groupedNote:
    '{grouped} trong số {typed} học sinh đã được chia nhóm — số {absent} vắng mặt.',
  modeLabel: 'Phân chia theo',
  modePerGroup: 'Số học sinh trong mỗi nhóm',
  modeGroupCount: 'Số lượng nhóm',
  groupSizeLabel: 'Học sinh trong mỗi nhóm',
  groupCountLabel: 'Có bao nhiêu nhóm',
  sexMixLabel: 'Phân chia nam và nữ một cách cân bằng',
  sexSeparateLabel: 'Giữ các bé trai và bé gái riêng biệt',
  sexWhyNoList:
    'Hãy thêm học sinh của bạn vào phần “Thông tin học sinh” và chọn M hoặc F cho từng em để sử dụng các tính năng này.',
  sexWhyUnset:
    '{unset} trong số {grouped} học sinh đang được phân nhóm chưa được chỉ định giới tính. Hãy mở “Thông tin học sinh” và chọn M hoặc F cho các em để có thể sử dụng các tùy chọn này.',
  sexWhyReturning:
    '{who} đã quay lại nhưng chưa được gán giới tính. Các tùy chọn này yêu cầu phải có thông tin về giới tính cho từng học sinh trong nhóm.',
  leftoversLabel: 'Nếu vẫn còn học sinh',
  leftoversSpread: 'Chia đều các em vào các nhóm',
  leftoversBunch: 'Gộp tất cả vào một nhóm',
  leftoversHelp:
    'Dù thế nào đi nữa, không có nhóm nào có quy mô nhỏ hơn quy mô mà bạn đã chọn.',
  soundOn: 'Bật âm thanh',
  soundOff: 'Tắt âm thanh',
  speedLabel: 'Tốc độ',
  speedNormal: 'Bình thường',
  speedFast: 'Nhanh',
  speedSkip: 'Bỏ qua hoạt ảnh',
  sectionStudentsHeading: 'Thông tin học sinh',
  sectionGroupingHeading: 'Các tùy chọn phân nhóm',
  sectionImportExportHeading: 'Nhập / xuất',
  sectionSoundHeading: 'Âm thanh và hoạt ảnh',
  rosterColNumber: '#',
  rosterColName: 'Tên',
  rosterColSex: 'Giới tính',
  rosterColAbsent: 'Vắng mặt',
  rosterColTogether: 'Cùng nhau',
  rosterColApart: 'Tách biệt',
  rosterUnset: '—',
  rosterSexMale: 'M',
  rosterSexFemale: 'F',
  rosterAddStudent: '+ Thêm học sinh',
  rosterAddSeveral: '+ Thêm một vài…',
  rosterHowMany: 'Thêm bao nhiêu?',
  rosterAddConfirm: 'Thêm',
  rosterAbsentPill: 'vắng mặt',
  rosterAbsentConsequence:
    'Học sinh được ghi là vắng mặt sẽ không được tính vào khi chia nhóm.',
  rosterCountLine: '{total} học sinh · {here} có mặt · {absent} vắng mặt',
  rosterDuplicateMessage:
    'Số {number} đã được {name} sử dụng. Mỗi học sinh cần có một số riêng.',
  rosterNoSexMessage:
    '{names} vẫn cần ghi M hoặc F. Mỗi học sinh đều phải có một trong hai ký hiệu này thì mới có thể chia nhóm được.',
  rosterClashMessage:
    '{names} được xếp cùng nhau, nên không thể đồng thời tách biệt các em.',
  rosterGapWarning:
    'Danh sách lớp của bạn có vẻ chưa đầy đủ. Thiếu các học sinh mang số {missing}. Nếu những em học sinh đó đã chuyển trường thì không sao cả — hãy mở phần “Thông tin học sinh” để kiểm tra.',
  rosterOpenRefusedMessage:
    'Thông tin học sinh có thể chứa tối đa {max} học sinh. Hãy giảm con số này để hiển thị lớp học này dưới dạng danh sách riêng lẻ.',
  rosterAtLimitMessage:
    'Thông tin học sinh có thể chứa tối đa {max} học sinh. Hãy xóa một học sinh để thêm học sinh khác.',
  rosterRoomMessage: 'Vẫn còn chỗ cho {room} học sinh nữa.',
  rosterRemove: 'Xóa',
  rosterClearAll: 'Xóa tất cả',
  stateNoneAdded: 'chưa có mục nào được thêm vào',
  stateNamed: '{n} đã có tên',
  stateAbsent: '{n} vắng mặt',
  stateTogether: '{n} cùng nhau',
  stateApart: '{n} tách biệt',
  stateAdded: '{n} đã được thêm vào',
  stateNone: 'không có',
  stateMixed: 'nam và nữ cân bằng',
  stateSeparated: 'phân chia theo giới tính',
  stateBunched: 'học sinh còn lại gộp vào một nhóm',
  stateNothingToSave: 'chưa có gì để lưu cả',
  stateUnsaved: 'các thay đổi chưa được lưu — hãy xuất để giữ lại chúng',
  makeGroups: 'Tạo nhóm',
  again: 'Trộn lại',
  needsJs: 'Công cụ này yêu cầu bật JavaScript.',
  resultsHeading: 'Các nhóm của bạn',
  resultsHeadingNamed: '{className} — các nhóm của bạn',
  resultsSummary: '{groups} nhóm từ {students} học sinh.',
  groupLabel: 'Nhóm {n}',
  studentNumber: 'Học sinh {n}',
  staleMode: 'Các nhóm này đã lỗi thời — quy mô nhóm đã thay đổi.',
  staleLeftovers:
    'Các nhóm này đã lỗi thời — lựa chọn “học sinh còn lại” đã thay đổi.',
  staleSexMode:
    'Các nhóm này đã lỗi thời — cách phân nhóm các em trai và em gái đã thay đổi.',
  staleRoster: 'Các nhóm này đã lỗi thời — danh sách lớp đã thay đổi.',
  csvProblemEmptyFile: 'Tệp này trống.',
  csvProblemUnreadable: 'Không thể đọc được tệp đó. Hãy thử chọn lại tệp đó.',
  csvProblemNoNumberColumn:
    'Tệp này không có cột số. Mỗi học sinh cần có số thứ tự.',
  csvProblemNumberBlank:
    'Dòng {row} — chưa có số thứ tự. Mỗi học sinh cần có một số.',
  csvProblemNumberNotWhole:
    "Dòng {row} — số '{value}' không phải là số nguyên.",
  csvProblemDuplicateNumber:
    'Dòng {row} — số {value} đã được dòng {firstRow} sử dụng.',
  csvProblemSex:
    "Dòng {row} — giới tính '{value}' không được nhận diện. Hãy sử dụng {accepted} hoặc để trống.",
  csvProblemAbsent:
    "Dòng {row} — vắng mặt '{value}' không được nhận diện. Hãy sử dụng {accepted} hoặc để trống.",
  csvProblemLetter:
    "Dòng {row} — {column} '{value}' không phải là một ký tự duy nhất.",
  csvProblemTooMany:
    'Tệp này có {found} học sinh. “Thông tin học sinh” chứa được tối đa {max} học sinh.',
  csvWrongLanguage:
    'Đây có vẻ là một danh sách lớp bằng {language}. Hãy mở phiên bản {version} của trang này để nhập nó.',
  csvLanguageName: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  csvLanguageVersion: {
    en: 'Tiếng Anh',
    id: 'Tiếng Indonesia',
    zh: 'Tiếng Trung',
    vi: 'Tiếng Việt',
    th: 'Tiếng Thái',
  },
  ioExportClassList: 'Xuất danh sách lớp',
  ioExportGroups: 'Xuất nhóm',
  ioDownloadTemplate: 'Tải xuống mẫu',
  ioImportLabel: 'Nhập danh sách lớp học',
  ioProblemsHeading: 'Tệp này chưa được nhập:',
  ioReplaceWarning:
    'Danh sách này sẽ thay thế danh sách lớp hiện tại của bạn — {total} học sinh, {named} em đã có tên.',
  ioReplaceConfirm: 'Thay thế nó',
  ioReplaceCancel: 'Giữ lại những gì tôi đang có',
  ioImported: 'Đã nhập {total} học sinh.',
  ioBothLanguages: 'Cũng xuất sang ngôn ngữ khác',
  ioBothLanguagesHint:
    'Tệp của bạn hiện đã được lưu lại bằng ngôn ngữ này. Một tab thứ hai sẽ mở ra bằng ngôn ngữ bạn đã chọn, với danh sách lớp học giống hệt, để bạn kiểm tra và lưu lại tại đó. Không có dữ liệu nào được lưu trữ và cũng không có dữ liệu nào được gửi đi đâu cả.',
  ioHandoverBlocked:
    'Không thể mở tab thứ hai. Danh sách lớp học của bạn vẫn còn ở đây — hãy cho phép cửa sổ bật lên và thử lại.',
  ioHandoverTimedOut:
    'Tab thứ hai chưa bao giờ yêu cầu danh sách lớp. Danh sách lớp của bạn vẫn còn ở đây — hãy đóng tab đó lại và thử lại.',
  ioHandoverNotOffered:
    'Chưa nhận được danh sách lớp. Hãy quay lại tab khác và thử lại.',
  ioHandoverSent: 'Danh sách lớp học của bạn hiện đã được mở tại {language}.',
  printOpen: 'In',
  printHeading: 'In',
  printWhat: 'Nội dung cần in',
  printWhatClassList: 'Danh sách lớp',
  printWhatGroups: 'Kết quả chia nhóm',
  printWhatBoth: 'Cả hai',
  printOnTheClassList: 'Trong danh sách lớp',
  printShowAbsent: 'Hiển thị danh sách học sinh vắng mặt',
  printShowLetters: 'Hiển thị giới tính và các chữ cái "cùng nhau"/"tách biệt"',
  printIncludeAvatars: 'Thêm ảnh đại diện',
  printCancel: 'Hủy',
  printConfirm: 'In',
  printClassListHeading: 'Danh sách lớp',
  printGroupsHeading: 'Các nhóm',
  printedOn: 'In ngày {on}',
  printHereToday: '{here} học sinh có mặt hôm nay · {absent} vắng mặt',
  boardOpen: 'Toàn màn hình',
  boardExit: 'Thoát chế độ toàn màn hình',
  boardShuffle: 'Trộn lại',
  staleRefuseExport:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi lưu chúng.',
  staleRefusePrint:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi in chúng.',
  staleRefuseBoard:
    'Các nhóm này đã lỗi thời. Hãy trộn lại trước khi hiển thị chúng.',
  errors: {
    NO_STUDENTS:
      'Thêm một số học sinh vào, hoặc đảm bảo rằng ít nhất một trong số các em đó không bị ghi là vắng mặt.',
    TOO_MANY_STUDENTS:
      'Số học sinh đó vượt quá số lượng mà công cụ này có thể xử lý. Số lượng tối đa là {max}.',
    DUPLICATE_NUMBER:
      'Số học sinh {number} đã được sử dụng hai lần. Hãy cấp cho mỗi học sinh một số riêng.',
    INVALID_GROUP_SIZE: 'Mỗi nhóm cần có ít nhất 1 học sinh.',
    INVALID_GROUP_COUNT: 'Bạn cần có ít nhất 1 nhóm.',
    TOO_MANY_GROUPS:
      'Số lượng học sinh không đủ để chia thành nhiều nhóm như vậy. Số lượng nhóm tối đa mà bạn có thể lập là {max}.',
    TOGETHER_APART_CLASH:
      '{names} được đánh dấu để vừa ở cùng nhau, vừa phải tách biệt khỏi nhau. Hãy loại bỏ chữ cái biểu thị “ở cùng nhau” hoặc chữ cái biểu thị “tách biệt” khỏi một trong số các em.',
    TOGETHER_UNIT_TOO_LARGE:
      'Chữ cái "{letter}" có {unit} học sinh, nhưng nhóm lớn nhất ở đây chỉ chứa được {groupSize} học sinh. Hãy tăng quy mô các nhóm lên, hoặc phân chữ cái "{letter}" cho ít học sinh hơn.',
    TOGETHER_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành {groupsTried} nhóm mà vẫn giữ được những học sinh cần ở cùng nhau lại với nhau. Hãy tăng quy mô các nhóm lên, hoặc chia mỗi chữ cái cho ít học sinh hơn.',
    TOGETHER_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái “cùng nhau” nên không thể xử lý hết. Hãy thử dùng ít chữ cái hơn, hoặc tăng quy mô các nhóm.',
    KEEP_APART_IMPOSSIBLE:
      '{names} đều phải được tách biệt với nhau, do đó bạn sẽ cần ít nhất {groupsNeeded} nhóm. Hãy tạo thêm nhóm hoặc loại bỏ một trong các quy tắc.',
    KEEP_APART_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành {groupsTried} nhóm mà vẫn tách biệt tất cả những học sinh cần được tách biệt. Hãy tạo thêm nhóm hoặc loại bỏ một trong các quy tắc.',
    KEEP_APART_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều quy tắc xếp khác nhóm, khó mà xử lý hết được. Hãy thử loại bỏ một số quy tắc trong số đó.',
    BOTH_RULES_NO_ARRANGEMENT:
      'Không có cách nào để chia lớp của bạn thành {groupsTried} nhóm mà vẫn đáp ứng đồng thời mọi chữ cái “cùng nhau” và mọi chữ cái “tách biệt”. Quá trình tìm kiếm không thể xác định được loại quy tắc nào gây ra vấn đề, vì vậy hãy thử một trong hai cách: tăng quy mô các nhóm hoặc gán một chữ cái “cùng nhau” cho ít học sinh hơn; hoặc tạo thêm nhóm hoặc bỏ một trong các quy tắc “tách biệt”.',
    BOTH_RULES_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái “cùng nhau” và “tách biệt” để có thể xử lý hết cùng một lúc. Hãy thử dùng ít chữ cái hơn ở cả hai loại, hoặc tăng quy mô các nhóm.',
    SEX_NEEDS_ALL_SET:
      '{names} chưa được chỉ định giới tính, do đó chế độ này sẽ không thể hoạt động cho đến khi tất cả học sinh đều được chỉ định. Hãy chỉ định giới tính cho từng em hoặc tắt tính năng này đi.',
    SEX_SEPARATE_SPLITS_UNIT:
      '{names} được đánh dấu để ở cùng nhau, nhưng không phải tất cả đều cùng giới tính, nên họ không thể tạo thành một nhóm cùng giới. Hãy gỡ bỏ chữ “cùng nhau” khỏi một trong số họ, hoặc tắt chế độ này đi.',
    SEX_SEPARATE_IMPOSSIBLE:
      'Không thể chia các em trai và em gái thành các nhóm riêng biệt trong {groupsRequested} nhóm mà vẫn đảm bảo tuân thủ các quy tắc khác của bạn. Hệ thống tìm kiếm không thể xác định được quy tắc nào là nguyên nhân gây ra vấn đề, vì vậy hãy thử một trong hai cách khắc phục sau: yêu cầu số lượng nhóm khác hoặc tắt chế độ này.',
    SEX_SEPARATE_SEARCH_GAVE_UP:
      'Ở đây có quá nhiều chữ cái “cùng nhau” và “tách biệt” để xử lý hết trong khi vẫn phải xếp nam và nữ vào các nhóm riêng. Hãy thử dùng ít chữ cái hơn hoặc tắt chế độ này đi.',
    PINNED_SPLITS_UNIT:
      '{names} được đánh dấu để ở cùng nhau, nhưng chỉ một số người trong số họ nằm trong nhóm được ghim. Hãy bỏ ghim nhóm đó, hoặc gỡ bỏ ký hiệu “ở cùng nhau” khỏi những người nằm ngoài nhóm.',
    PINNED_APART_CLASH:
      '{names} đã được đánh dấu “tách biệt” với nhau, nhưng một nhóm được ghim lại xếp các em vào cùng một nhóm. Hãy bỏ ghim nhóm đó, hoặc gỡ chữ cái “tách biệt” khỏi một trong số các em.',
    PINNED_IN_TWO_GROUPS:
      '{name} hiện đang được ghim vào hai nhóm khác nhau cùng một lúc. Một học sinh chỉ có thể được ghim vào một nhóm. Hãy gỡ học sinh đó ra khỏi một trong hai nhóm.',
    PINNED_TOO_MANY_GROUPS:
      '{situation, select, over {Các nhóm bạn đã ghim hiện đã dùng {pinnedGroupCount} nhóm — nhiều hơn số {requestedGroups} nhóm mà bạn đã yêu cầu — khiến {remainingStudents} học sinh không còn nhóm nào dành cho mình. Hãy bỏ ghim một nhóm hoặc yêu cầu thêm nhóm.} full {Các nhóm bạn đã ghim hiện đã chiếm {pinnedGroupCount} trong tổng số {requestedGroups} nhóm mà bạn đã yêu cầu, nên {remainingStudents} học sinh còn lại không còn nhóm nào dành cho mình. Hãy bỏ ghim một nhóm hoặc yêu cầu thêm nhóm.} other {Các nhóm bạn đã ghim đã chiếm {pinnedGroupCount} trong số {requestedGroups} nhóm mà bạn yêu cầu, do đó chỉ còn lại {remainingStudents} học sinh — con số này không đủ để tạo {poolGroupsNeeded} nhóm còn thiếu. Hãy bỏ ghim một nhóm hoặc yêu cầu ít nhóm hơn.}}',
  },
  warnings: {
    SEX_SPILLOVER:
      '{sex, select, M {{names} đã gia nhập một nhóm các bạn nữ vì không có đủ bạn nam để thành lập một nhóm riêng. Đó chỉ đơn giản là do tỷ lệ giới tính như vậy, chứ không phải là một sai lầm cần khắc phục.} other {{names} đã gia nhập một nhóm các cậu bé vì không có đủ số lượng các bạn nữ để thành lập một nhóm riêng. Đó chỉ đơn giản là cách phân chia số lượng, chứ không phải là một sai lầm cần khắc phục.}}',
    PINNED_MIXED_SEX:
      '{names} được ghim cùng nhau thành một nhóm, nhưng không phải tất cả đều cùng giới tính, nên nhóm này không được chia theo giới tính như các nhóm khác. Đó chính là điều bạn yêu cầu khi ghim nhóm, chứ không phải là một sai sót cần sửa.',
    SEX_BOTH_TOO_SMALL:
      '{names} đã được xếp vào một nhóm chung vì số lượng của cả hai giới đều không đủ để thành lập một nhóm riêng. Đó chỉ đơn giản là cách phân chia theo số lượng, chứ không phải là một sai sót cần sửa chữa.',
  },
};
