import type { Catalogue } from './en';

/**
 * zh — generated by `scripts/i18n-scaffold.mjs` from en.ts and the DeepL
 * cache (#22), then REVIEWED BY HAND. Re-rendering discards those reviews, so
 * the generator refuses to overwrite this file without `--force`.
 *
 * Every message is a template rebuilt from DeepL's translation of the
 * sentences it can say, and checked to fill exactly the slots English fills
 * (#136).
 *
 * MACHINE-TRANSLATED COPY IS A FIRST DRAFT. It has been checked for structure
 * — placeholders intact, protected names preserved, nothing empty — and NOT
 * for fluency, which needs a speaker of this language.
 */
export const zh: Catalogue = {
  title: '课堂小组创建器',
  description:
    '立即将班级分成小组——直接在浏览器中完成，无需向任何地方发送数据。',
  heading: '课堂小组创建器',
  lead: '由Shyden专为教师打造。公平地给全班分组需要花费您本就不多的时间，而手动操作又容易引发关于“偏袒”的争议。只需一次点击，即可完成分组——完全免费，无需注册，且有关您班级的信息绝不会离开您的浏览器。',
  privacy: '所有操作都在您的浏览器中完成。班级名单绝不会离开此页面。',
  howToHeading: '使用方法',
  howToWhat:
    '只需输入班级人数以及每组希望安排多少名学生，系统就会自动将学生随机分组，确保每个小组的人数都不会少于您设定的最低人数。',
  howToSteps: [
    '填写你班上的学生人数。',
    '选择如何给他们分组。',
    '点击“开始分组”。',
  ],
  classLabel: '班级（可选）',
  studentsLabel: '学生人数',
  studentsHelp: '学生均为匿名，并按编号区分——学生1、学生2，依此类推。',
  studentsLockedReason:
    '由您的列表设定。如需修改，请在“学生详情”中添加或移除学生。',
  // #188. DeepL draft, awaiting a speaker (#53, #161). The three labels are
  // short -- the class that shipped a wrong-sense translation on a pupil
  // roster before -- so they need reviewing apart from the sentences.
  absentNumbersLabel: '学生编号',
  keepTogetherLabel: '同组',
  keepApartLabel: '分开',
  absentNumbersHelp: '缺席学生的学生编号，用逗号分隔。',
  pairNumbersHelp: '逗号连接一对；分号开始新的一对——3,9; 14,15。',
  numbersLockedReason:
    '由您的列表设定。如需修改，请在“学生详情”中标记缺席和配对。',
  numbersNotWholeMessage: '“{text}”不是整数。请输入 1 到 {count} 之间的学号。',
  numbersAboveCountMessage: '没有 {text} 号。您有 {count} 名学生。',
  numbersAboveMaximumMessage: '没有 {text} 号。本页面最多支持 {max} 名学生。',
  numbersDuplicateMessage: '{text} 号出现了两次。每个编号只能出现在一处。',
  numbersLonelySetMessage: '一对至少需要两个编号，而 {text} 只有一个。',
  numbersTooManySetsMessage: '配对数量超出本页面的上限。{text} 多出了一对。',
  numbersNoCountMessage: '请先填写学生人数。',
  // No plural wrapper: Chinese has only the `other` category, the same shape
  // `rosterGapWarning` below already uses for its {missing} slot.
  groupedNote: '{typed} 人中有 {grouped} 人已分组——{absent} 号缺席。',
  modeLabel: '按……划分',
  modePerGroup: '每组学生人数',
  modeGroupCount: '组数',
  groupSizeLabel: '每个小组的学生',
  groupCountLabel: '有多少个小组',
  sexMixLabel: '将男生和女生平均分配',
  sexSeparateLabel: '让男生和女生分开',
  sexWhyNoList:
    '在“学生详情”中添加您的学生，并为每位学生设置“M”或“F”，以便使用这些功能。',
  sexWhyUnset:
    '在被分组的{grouped}名学生中，有{unset}名学生的性别未设置。请打开“学生详情”页面，为他们设置“M”或“F”，以便使用这些功能。',
  sexWhyReturning:
    '{who} 已不再标记为缺席，但未设置性别。这些选项需要为每个被分组的学生分别设置。',
  leftoversLabel: '如果还有剩余的学生',
  leftoversSpread: '把他们平均分到各组',
  leftoversBunch: '把他们全都放进同一个组',
  leftoversHelp: '无论哪种情况，任何一组的人数都不会少于你所选的数量。',
  soundOn: '声音：开',
  soundOff: '声音：关',
  speedLabel: '速度',
  speedNormal: '正常',
  speedFast: '快',
  speedSkip: '跳过动画',
  sectionStudentsHeading: '学生详情',
  sectionGroupingHeading: '分组选项',
  sectionImportExportHeading: '导入 / 导出',
  sectionSoundHeading: '声音和动画',
  rosterColNumber: '#',
  rosterColName: '姓名',
  rosterColSex: '性别',
  rosterColAbsent: '缺席',
  rosterColTogether: '在一起',
  rosterColApart: '分开',
  rosterUnset: '—',
  rosterSexMale: 'M',
  rosterSexFemale: 'F',
  rosterAddStudent: '+ 添加学生',
  rosterAddSeveral: '+ 添加几个……',
  rosterHowMany: '要加多少？',
  rosterAddConfirm: '添加',
  rosterAbsentPill: '缺席',
  rosterAbsentConsequence: '在分组时，被标记为缺席的学生不会被纳入其中。',
  rosterCountLine: '{total} 名学生 · {here} 在场 · {absent} 缺席',
  rosterDuplicateMessage:
    '编号 {number} 已被 {name} 占用。每位学生都需要一个专属编号。',
  rosterNoSexMessage:
    '{names} 仍需标注 M 或 F。在分组之前，每位学生都必须标注一项。',
  rosterClashMessage: '{names} 被放在一起，因此无法再把他们分开。',
  rosterGapWarning:
    '你的班级名单似乎不完整。缺少 {missing} 号的学生。如果这些学生已经转学，那也没关系——请打开“学生详情”进行核对。',
  rosterOpenRefusedMessage:
    '“学生详情”最多可显示 {max} 名学生。若要单独列出该班级，请降低该数值。',
  rosterAtLimitMessage:
    '“学生详情”最多可容纳 {max} 名学生。若要添加另一名学生，请先移除一名学生。',
  rosterRoomMessage: '还有{room}个名额。',
  rosterRemove: '删除',
  rosterClearAll: '清除全部',
  stateNoneAdded: '未添加',
  stateNamed: '{n} 已命名',
  stateAbsent: '{n} 缺席',
  stateTogether: '{n} 一起',
  stateApart: '{n} 分开',
  stateAdded: '{n} 已添加',
  stateNone: '无',
  stateMixed: '男女平均分配',
  stateSeparated: '按性别划分',
  stateBunched: '剩余学生归入同一组',
  stateNothingToSave: '目前尚无内容可保存',
  stateUnsaved: '未保存的更改 — 导出以保留这些更改',
  makeGroups: '开始分组',
  again: '重新洗牌',
  needsJs: '此工具需要启用 JavaScript。',
  resultsHeading: '您的分组',
  resultsHeadingNamed: '{className} — 您的分组',
  resultsSummary: '{groups} 个小组，由 {students} 名学生组成。',
  groupLabel: '{n} 组',
  studentNumber: '学生 {n}',
  staleMode: '这些分组已经过时了——每组人数发生了变化。',
  staleLeftovers: '这些分组已经过时了——“剩余学生”选项已经更改了。',
  staleSexMode: '这些分组已经过时了——男女生的分组方式已经发生了变化。',
  staleRoster: '这些组已经过时了——班级名单已经变更。',
  csvProblemEmptyFile: '该文件为空。',
  csvProblemUnreadable: '无法读取该文件。请重新选择该文件。',
  csvProblemNoNumberColumn: '该文件中没有编号列。每个学生都需要一个编号。',
  csvProblemNumberBlank: '行 {row} — 编号处为空。每位学生都需要一个。',
  csvProblemNumberNotWhole: "行 {row} — 编号 '{value}' 不是整数。",
  csvProblemDuplicateNumber: '行 {row} — 编号 {value} 已被行 {firstRow} 占用。',
  csvProblemSex:
    "行 {row} — 性别 '{value}' 无法识别。请使用 {accepted}，或留空。",
  csvProblemAbsent:
    "行 {row} — 缺席 '{value}' 无法识别。请使用 {accepted}，或留空。",
  csvProblemLetter: "第{row}行 — {column} '{value}' 不是单个字母。",
  csvProblemTooMany:
    '该文件中包含 {found} 名学生。“学生详情”最多可容纳 {max} 名学生。',
  csvWrongLanguage:
    '这看起来像是一份 {language} 班级名单。请打开该页面的 {version} 版本以导入它。',
  csvLanguageName: {
    en: '英语',
    id: '印尼语',
    zh: '中文',
    vi: '越南语',
    th: '泰语',
  },
  csvLanguageVersion: {
    en: '英语',
    id: '印尼语',
    zh: '中文',
    vi: '越南语',
    th: '泰语',
  },
  ioExportClassList: '导出班级名单',
  ioExportGroups: '导出分组',
  ioDownloadTemplate: '下载模板',
  ioImportLabel: '导入班级名单',
  ioProblemsHeading: '未导入此文件：',
  ioReplaceWarning:
    '这将取代您当前的班级名单——{total}名学生，其中{named}名已命名。',
  ioReplaceConfirm: '替换它',
  ioReplaceCancel: '保留当前名单',
  ioImported: '已导入 {total} 名学生。',
  ioBothLanguages: '还以另一种语言导出',
  ioBothLanguagesHint:
    '您的文件现已以该语言保存。系统会以您选择的语言打开第二个标签页，其中显示相同的班级名单，供您核对并保存。系统不会存储任何内容，也不会将任何信息发送至任何地方。',
  ioHandoverBlocked:
    '无法打开第二个标签页。您的班级名单仍在此页面——请允许弹出窗口，然后重试。',
  ioHandoverTimedOut:
    '第二个标签页没有请求班级名单。您的班级名单仍在此页面——请关闭那个标签页，然后重试。',
  ioHandoverNotOffered: '没有收到班级名单。请返回另一个标签页，然后重试。',
  ioHandoverSent: '您的班级名单现已以{language}打开。',
  printOpen: '打印',
  printHeading: '打印',
  printWhat: '打印内容',
  printWhatClassList: '班级名单',
  printWhatGroups: '分组结果',
  printWhatBoth: '两者',
  printOnTheClassList: '在班级名单上',
  printShowAbsent: '显示缺席的学生',
  printShowLetters: '显示性别以及“在一起/分开”的字母',
  printIncludeAvatars: '包含头像',
  printCancel: '取消',
  printConfirm: '打印',
  printClassListHeading: '班级名单',
  printGroupsHeading: '组',
  printedOn: '打印于 {on}',
  printHereToday: '{here} 今天到校的学生 · {absent} 缺席的学生',
  boardOpen: '全屏',
  boardExit: '退出全屏模式',
  boardShuffle: '重新洗牌',
  staleRefuseExport: '这些分组已经过时了。保存前请重新洗牌。',
  staleRefusePrint: '这些分组已经过时了。打印前请重新洗牌。',
  staleRefuseBoard: '这些分组已经过时了。显示前请重新洗牌。',
  errors: {
    NO_STUDENTS: '添加一些学生，或者确保其中至少有一人未被标记为缺席。',
    TOO_MANY_STUDENTS: '该工具最多只能处理 {max} 名学生。',
    DUPLICATE_NUMBER:
      '学生编号 {number} 被重复使用了两次。请给每位学生分配一个唯一的编号。',
    INVALID_GROUP_SIZE: '每个小组至少需要1名学生。',
    INVALID_GROUP_COUNT: '您至少需要创建1个小组。',
    TOO_MANY_GROUPS: '学生人数不足以分成这么多组。最多只能分成 {max} 组。',
    TOGETHER_APART_CLASH:
      '{names} 既被标记为“在一起”，又被标记为“分开”。请从其中一个中移除“在一起”或“分开”的字母。',
    TOGETHER_UNIT_TOO_LARGE:
      '有 {unit} 名学生带有字母“{letter}”，但这里最大的小组只能容纳 {groupSize} 人。请扩大小组规模，或者把字母“{letter}”分配给更少的学生。',
    TOGETHER_NO_ARRANGEMENT:
      '无论如何都无法将你的班级分成 {groupsTried} 个小组，同时又让所有需要待在一起的学生保持在一起。要么扩大每个小组的规模，要么将每个字母分配给更少的学生。',
    TOGETHER_SEARCH_GAVE_UP:
      '这里的“在一起”字母太多，难以逐一处理。请尝试减少字母数量，或者扩大小组。',
    KEEP_APART_IMPOSSIBLE:
      '{names} 都需要彼此分开，因此你至少需要 {groupsNeeded} 个组。要么增加组数，要么删除其中一条规则。',
    KEEP_APART_NO_ARRANGEMENT:
      '无法将你的班级分成 {groupsTried} 个小组，同时把所有需要分开的学生都分到不同组。要么增加小组数量，要么取消其中一条规则。',
    KEEP_APART_SEARCH_GAVE_UP:
      '这里的“分开”规则太多，难以逐一处理。试着删除其中一些吧。',
    BOTH_RULES_NO_ARRANGEMENT:
      '无法将你的班级分成 {groupsTried} 个小组，同时满足所有“在一起”字母和所有“分开”字母。系统无法判断是哪一类规则造成了问题，因此请尝试以下任一方法：扩大小组，或者把某个“在一起”字母分配给更少的学生；或者增加小组数量，或者取消其中一条“分开”规则。',
    BOTH_RULES_SEARCH_GAVE_UP:
      '这里的“在一起”和“分开”字母太多，无法一次全部处理。请尝试减少任一类字母的数量，或者扩大小组。',
    SEX_NEEDS_ALL_SET:
      '{names} 未设置性别，因此在此模式下，必须先为每位学生设置性别，该模式才能运行。请为每位学生设置性别，或关闭此功能。',
    SEX_SEPARATE_SPLITS_UNIT:
      '{names} 已被标记为“在一起”，但并非全是同一性别，因此无法组成单一性别的小组。请从其中一人身上移除“在一起”字母，或关闭此模式。',
    SEX_SEPARATE_IMPOSSIBLE:
      '在 {groupsRequested} 个小组中，无法同时满足将男生和女生分在不同小组以及您设定的其他规则的要求。搜索功能无法确定是哪条规则导致了问题，因此请尝试以下任一解决方法：指定不同数量的小组，或者关闭此模式。',
    SEX_SEPARATE_SEARCH_GAVE_UP:
      '这里的“在一起”和“分开”字母太多，无法在把男孩和女孩分到不同组的同时完成分组。请尝试减少字母数量，或者关闭此模式。',
    PINNED_SPLITS_UNIT:
      '{names} 已被标记为“保持在一起”，但其中只有一部分被归入固定组。请取消固定该组，或者将组外人员的“保持在一起”标记移除。',
    PINNED_APART_CLASH:
      '{names} 已被标记为“分开”，但一个固定的组把他们放进了同一组。请取消固定该组，或从其中一人身上移除“分开”字母。',
    PINNED_IN_TWO_GROUPS:
      '{name} 同时被固定在两个不同的组中。一名学生只能被固定在一个组中。请将其从其中一个组中移除。',
    PINNED_TOO_MANY_GROUPS:
      '{situation, select, over {您固定的组已占用 {pinnedGroupCount} 个组——超过了您要求的 {requestedGroups} 个组——导致 {remainingStudents} 名学生无组可去。请取消固定一个组，或者增加组数。} full {您固定的组已占满您要求的 {requestedGroups} 个组中的 {pinnedGroupCount} 个，剩下的 {remainingStudents} 名学生已无组可去。请取消固定一个组，或者增加组数。} other {您已将所请求的 {requestedGroups} 个小组中的 {pinnedGroupCount} 个小组固定，这意味着只剩下 {remainingStudents} 名学生——这不足以组成仍需的 {poolGroupsNeeded} 个小组。请取消固定一个小组，或者减少请求的小组数量。}}',
  },
  warnings: {
    SEX_SPILLOVER:
      '{sex, select, M {{names}加入了一个女生组，因为男生人数不足，无法单独组成一个组。这纯粹是人数分配的结果，并非需要纠正的错误。} other {{names} 加入了一个男孩小组，因为女孩人数不足，无法单独组成一个小组。这只是人数分配的结果，并非需要纠正的错误。}}',
    PINNED_MIXED_SEX:
      '{names} 被一起固定在同一组里，但他们并非全是同一性别，因此这个组没有像其他组那样按性别划分。这正是固定分组所要求的，并不是需要更正的错误。',
    SEX_BOTH_TOO_SMALL:
      '{names} 被归入一个合并组，是因为无论哪一性别的人数都不够多，无法单独组成一个组。这只是人数分布的自然结果，并非需要更正的错误。',
  },
};
